# Site settings
title: Andy Granowitz
email: '&#097;&#110;&#100;&#121;&#046;&#103;&#114;&#097;&#110;&#111;&#119;&#105;&#116;&#122;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;'
description: > # this means to ignore newlines until "baseurl:"
  Personal website and blog of Andy Granowitz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.andygranowitz.com" # the base hostname & protocol for your site
twitter_username: agrano
github_username:  grano
highlighter: pygments

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      comments: true